name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install uv
        uv venv
        uv pip install -e ".[dev]"
    - name: Run tests with coverage
      run: |
        pytest mcp_tavily_search --cov=mcp_tavily_search --cov-report=xml --cov-report=term
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
    - name: Lint with flake8
      run: |
        uv pip install flake8
        flake8 mcp_tavily_search --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 mcp_tavily_search --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
